# Generated by Django 2.1.4 on 2018-12-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwikeeapp', '0006_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='sub_total',
            field=models.FloatField(),
        ),
    ]
