# Generated by Django 2.1.4 on 2018-12-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwikeeapp', '0007_auto_20181224_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
    ]
