# Generated by Django 2.1.4 on 2018-12-28 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwikeeapp', '0008_auto_20181224_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kwikeeapp.Driver'),
        ),
    ]
