# Generated by Django 2.1.4 on 2018-12-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwikeeapp', '0009_auto_20181228_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
