# Generated by Django 2.1.4 on 2018-12-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwikeeapp', '0010_auto_20181228_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
